// src/products.js
export const products = [
  {
    id: 1,
    name: "ProBook Ultra 14",
    category: "Laptops",
    price: 849,
    description: "14-inch laptop with Intel i7, 16GB RAM, 512GB SSD, 12-hour battery. Perfect for work and travel.",
  },
  {
    id: 2,
    name: "GameRig X900",
    category: "Laptops",
    price: 1499,
    description: "Gaming laptop with RTX 4070, 32GB RAM, 1TB SSD, 165Hz display. Dominates every game.",
  },
  {
    id: 3,
    name: "BudgetBook Go",
    category: "Laptops",
    price: 379,
    description: "Lightweight 15-inch laptop with 8GB RAM, 256GB SSD. Great for students and everyday tasks.",
  },
  {
    id: 4,
    name: "FitPulse Smart Watch",
    category: "Fitness",
    price: 129,
    description: "Tracks heart rate, steps, sleep, and workouts. 7-day battery, waterproof, GPS-enabled.",
  },
  {
    id: 5,
    name: "IronGrip Dumbbell Set",
    category: "Fitness",
    price: 89,
    description: "Adjustable 5-50lb dumbbell set with rack. Ideal for home gym strength training.",
  },
  {
    id: 6,
    name: "AeroRun Pro Treadmill",
    category: "Fitness",
    price: 699,
    description: "Foldable treadmill with 15 incline levels, built-in speakers, and workout programs.",
  },
  {
    id: 7,
    name: "SoundWave ANC Headphones",
    category: "Audio",
    price: 199,
    description: "Over-ear headphones with active noise cancellation, 30-hour battery, premium sound.",
  },
  {
    id: 8,
    name: "PodBuds Wireless",
    category: "Audio",
    price: 49,
    description: "True wireless earbuds, 6-hour playtime, IPX5 water resistant, touch controls.",
  },
  {
    id: 9,
    name: "StudioMix Speakers",
    category: "Audio",
    price: 299,
    description: "Bookshelf studio monitors with rich bass, Bluetooth 5.0, and optical input.",
  },
  {
    id: 10,
    name: "SnapShot DSLR 4K",
    category: "Cameras",
    price: 899,
    description: "24MP DSLR camera with 4K video, dual lens kit, weather-sealed body.",
  },
  {
    id: 11,
    name: "VlogCam Pocket",
    category: "Cameras",
    price: 349,
    description: "Compact 4K action camera with gimbal stabilization, 170° wide lens, waterproof.",
  },
  {
    id: 12,
    name: "ErgoDesk Chair Pro",
    category: "Office",
    price: 459,
    description: "Fully ergonomic office chair with lumbar support, adjustable armrests, 4D headrest.",
  },
  {
    id: 13,
    name: "UltraWide 34\" Monitor",
    category: "Office",
    price: 579,
    description: "34-inch curved ultrawide monitor, 144Hz, 1ms, USB-C 90W charging, IPS panel.",
  },
  {
    id: 14,
    name: "MechType Keyboard",
    category: "Office",
    price: 119,
    description: "Compact TKL mechanical keyboard, hot-swap switches, per-key RGB, USB-C.",
  },
  {
    id: 15,
    name: "YogaFlow Mat Pro",
    category: "Fitness",
    price: 65,
    description: "6mm thick non-slip yoga mat with alignment lines, carrying strap, eco-friendly material.",
  },
];